name: pupa
channels:
  - defaults
dependencies:
  - conda==24.7.1
  - conda-index==0.5.0
  - conda-package-streaming==0.10.0 # from git branch with 'create' feature
  - flit==3.9.0
  - packaging >=24
  - pip==24.2
  - pytest>=7.4
  - pytest-cov==4.1.0
  - python-build==0.10.0
  - python==3.12.4
  - typer==0.9.0
  - pip:
    - pypi-simple==1.6.0
    - sqlalchemy==2.0.32
    - pkginfo==1.11.1
